### ISSUE TITLE
Shush [WIP: 0.1]

### ISSUE THREAD

**Issue by Ashraf250** [noneofyourbusiness1415252/Maths-stuff#2]
https://replit.com/join/dtknejhg-ashraf500

A Preview

**Comment by noneofyourbusiness1415252** [comment]
Nice program! Let me know if you need any help on it. I would suggest linking it up to github like this:
![image](https://user-images.githubusercontent.com/80610051/115770437-9eda4200-a3a4-11eb-8d15-779f6d32bd96.png)
That way u can easily revert changes if u mess up ur code or it corrupts (just regularly commit ur changes to the repo) and other benefits.
